;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cdlatex-math-modify
        multiple-cursors-mode
        my-move-bol-or-prev-eol
        my-move-eol-or-next-bol
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        cdlatex-pbb
        compile
        next-buffer
        ns-open-file-select-line
        pixel-scroll-precision
        ))
